(() => {
 'use strict';
 const view=window.BiliSmoothView, api=window.chrome;
 if(!api?.runtime?.id||!api.tabs||!view)return;
 let tabId=Number(new URLSearchParams(location.search).get('tab'))||null,tabs=[],generation=0,issued=0,applied=0,timer=null,pending=false,closed=false,connected=false,tabRefreshTimer=null;
 const configKey='bilismooth.config.v4';
 function selected(){return tabs.find(tab=>tab.id===tabId)||null;}
 function empty(config=view.getSnapshot().config){return {config,media:{present:false},ranking:[],events:[]};}
 function schedule(){clearTimeout(timer);if(!closed&&!document.hidden)timer=setTimeout(()=>refresh(false),1200);}
 function stateError(error){const code=error?.message||'no-response';connected=false;view.setConnection(code==='stale-script'?'stale-script':tabId?'no-response':'no-video',selected());}
 async function readConfig(){const reply=await api.runtime.sendMessage({channel:'bilismooth-settings',action:'read'});if(!reply?.ok)throw Error(reply?.error||'settings-read-failed');view.applyConfig(reply.result);return reply.result;}
 async function queryTabs(){const previous=tabId;tabs=await api.tabs.query({url:['https://*.bilibili.com/*']});tabs=tabs.filter(tab=>Number.isInteger(tab.id));if(tabId&&!tabs.some(tab=>tab.id===tabId))tabId=null;if(!tabId&&tabs.length===1)tabId=tabs[0].id;if(previous!==tabId){generation++;connected=false;view.resetPending();view.setConnection(tabId?'connecting':'no-video',selected());}view.setVideos(tabs,tabId);return previous!==tabId;}
 async function request(action,patch){if(!tabId)throw Error('no-video');const reply=await api.tabs.sendMessage(tabId,{channel:'bilismooth',action,patch},{frameId:0});if(!reply?.ok)throw Error(reply?.error||'no-response');if(action!=='diagnostics'&&reply.result?.version!==api.runtime.getManifest().version)throw Error('stale-script');return reply.result;}
 async function refresh(reconnect=false){if(closed||document.hidden&&!reconnect)return;if(pending&&!reconnect)return;const token=generation,sequence=++issued;pending=true;clearTimeout(timer);try{if(reconnect){await queryTabs();await readConfig();}if(!tabId){connected=false;view.setConnection('no-video',null);return;}const result=await request('state');if(token!==generation||sequence<applied||closed)return;applied=sequence;connected=true;view.setConnection('connected',selected());view.renderSnapshot(result,true);}catch(error){if(token===generation&&sequence>=applied&&!closed){applied=sequence;stateError(error);}}finally{pending=false;schedule();}}
 async function selectTab(id){generation++;issued++;connected=false;view.resetPending();tabId=Number.isInteger(id)&&id>0?id:null;history.replaceState(null,'',location.pathname+(tabId?'?tab='+tabId:'')+location.hash);view.renderSnapshot(empty(),false);view.setConnection(tabId?'connecting':'no-video',selected());await queryTabs();await refresh(true);}
 async function patchGlobal(patch){const reply=await api.runtime.sendMessage({channel:'bilismooth-settings',action:'patch',patch});if(!reply?.ok)throw Error(reply?.error||'settings-save-failed');view.applyConfig(reply.result);return {...empty(reply.result),routeApplied:true};}
 async function command(action,patch){const token=generation,sequence=++issued;try{let result;if((action==='config'||action==='applyRoute')&&!connected){const value=action==='applyRoute'?{enabled:true,selection:'fixed',pcdnHost:patch?.host,mode:view.getSnapshot().config.mode==='off'?'bad-only':view.getSnapshot().config.mode}:patch;result=await patchGlobal(value);}else result=await request(action,patch);if(token!==generation)throw Error('selection-changed');if(action!=='diagnostics'&&sequence>=applied){applied=sequence;view.saveError(false);view.renderSnapshot(result,connected);}return result;}catch(error){if(token!==generation)throw Error('selection-changed');if(error.message==='settings-save-failed'){view.saveError(true);await readConfig().catch(()=>{});}else if(!['diagnostics','config','applyRoute'].includes(action))stateError(error);throw error;}finally{schedule();}}
 async function focusVideo(){if(!tabId)return;try{const tab=await api.tabs.update(tabId,{active:true});if(Number.isInteger(tab?.windowId))await api.windows.update(tab.windowId,{focused:true});}catch{stateError(Error('closed-tab'));await queryTabs();}}
 async function reloadVideo(){if(!tabId)return;try{await api.tabs.reload(tabId);view.setConnection('connecting',selected());view.toast(view.t('reloading'));schedule();}catch{stateError(Error('closed-tab'));}}
 async function setMotion(value){await api.storage.local.set({bilismoothMotion:value!==false});}
 window.BiliSmoothLive={command,refresh,selectTab,focusVideo,reloadVideo,setMotion};
 api.runtime.onMessage.addListener((message,sender,reply)=>{if(sender.id!==api.runtime.id||message?.channel!=='bilismooth-control')return;if(message.action==='locate'){api.tabs.getCurrent().then(tab=>reply({ok:!!tab?.id,tabId:tab?.id,version:document.querySelector('meta[name=bilismooth-version]')?.content||'',sourceTabId:tabId,hash:location.hash}),()=>reply({ok:false}));return true;}if(message.action!=='select-tab')return;selectTab(message.tabId).then(()=>reply({ok:true}),()=>reply({ok:false}));return true;});
 api.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes.bilismoothMotion)view.setMotion(changes.bilismoothMotion.newValue!==false);if(changes[configKey]?.newValue)view.applyConfig(changes[configKey].newValue);});
 function queueTabRefresh(){clearTimeout(tabRefreshTimer);tabRefreshTimer=setTimeout(async()=>{try{const changed=await queryTabs();if(!tabId)view.setConnection('no-video',null);else if(changed)await refresh(true);}catch{}},250);}
 api.tabs.onRemoved?.addListener(queueTabRefresh);api.tabs.onUpdated?.addListener(queueTabRefresh);api.tabs.onCreated?.addListener(queueTabRefresh);
 document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)refresh(true);});
 addEventListener('pagehide',()=>{closed=true;clearTimeout(timer);clearTimeout(tabRefreshTimer);});
 (async()=>{try{await readConfig();const saved=await api.storage.local.get('bilismoothMotion');view.setMotion(saved.bilismoothMotion!==false);await queryTabs();await refresh();}catch{view.toast(view.t('loadFailed'));stateError(Error('no-response'));schedule();}})();
})();
