import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('..', import.meta.url));
export async function buildMotion() {
  const result = await build({ absWorkingDir: root, entryPoints: ['src/ui/motion-entry.js'], bundle: true,
    format: 'iife', platform: 'browser', target: ['chrome120'], minify: true, write: false, metafile: true,
    legalComments: 'inline', define: { 'process.env.NODE_ENV': '"production"' } });
  const inputFiles = ['src/ui/motion-entry.js', 'scripts/build-motion.mjs', 'package-lock.json', ...Object.keys(result.metafile.inputs)];
  const runtime = '// Generated by scripts/build-motion.mjs. Motion MIT license: control/motion-LICENSE.txt\n' + result.outputFiles[0].text;
  await writeFile(path.join(root,'src/ui/motion-runtime.js'), runtime);
  const licenses = [...new Set(await Promise.all(['motion','framer-motion','motion-dom','motion-utils'].map(name=>readFile(path.join(root,'node_modules',name,'LICENSE.md'),'utf8'))))];
  await writeFile(path.join(root,'src/ui/control/motion-LICENSE.txt'), licenses.join('\n\n'));
  return [...new Set(inputFiles)];
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const inputs = await buildMotion(); console.log(JSON.stringify({ module: 'Motion mini + spring', inputs: inputs.length }));
}
